/**
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Command: npx gltfjsx@6.5.3 chairs001_2511072051_bake07.glb
 *
 * @format
 */

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
	const { nodes, materials } = useGLTF("/chairs001_2511072051_bake07.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes["12"].geometry}
				material={materials["マテリアル.016"]}
				position={[-6, 0, 10.392]}
				rotation={[0, -Math.PI / 6, 0]}
			/>
			<mesh
				geometry={nodes["11"].geometry}
				material={materials["マテリアル.015"]}
				position={[-10.392, 0, 6]}
				rotation={[Math.PI / 2, 0, Math.PI / 3]}
				scale={0.01}
			/>
			<mesh
				geometry={nodes["10"].geometry}
				material={materials["マテリアル.014"]}
				position={[-12, 0, 0]}
				rotation={[0, -1.571, 0]}
			/>
			<mesh
				geometry={nodes["09"].geometry}
				material={materials["マテリアル.012"]}
				position={[-10.392, 0, -6]}
				rotation={[Math.PI, -Math.PI / 3, Math.PI]}
			/>
			<mesh
				geometry={nodes["08"].geometry}
				material={materials["マテリアル.010"]}
				position={[-6, 0, -10.392]}
				rotation={[Math.PI, -Math.PI / 6, Math.PI]}
			/>
			<mesh
				geometry={nodes["07"].geometry}
				material={materials["マテリアル.009"]}
				position={[0, 0, -12]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
			<mesh
				geometry={nodes["06"].geometry}
				material={materials["マテリアル.008"]}
				position={[6, 0, -10.392]}
				rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
			/>
			<mesh
				geometry={nodes["05"].geometry}
				material={materials["マテリアル.007"]}
				position={[10.392, 0, -6]}
				rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
			/>
			<mesh
				geometry={nodes["04"].geometry}
				material={materials["マテリアル.006"]}
				position={[12, 0, 0]}
				rotation={[0, 1.571, 0]}
			/>
			<mesh
				geometry={nodes["03"].geometry}
				material={materials["マテリアル.004"]}
				position={[10.392, 0, 6]}
				rotation={[0, Math.PI / 3, 0]}
			/>
			<mesh
				geometry={nodes["02"].geometry}
				material={materials["マテリアル.005"]}
				position={[6, 0, 10.392]}
				rotation={[0, Math.PI / 6, 0]}
			/>
			<mesh
				geometry={nodes["01"].geometry}
				material={materials["マテリアル.017"]}
				position={[0, 0, 12]}
			/>
			<mesh
				geometry={nodes.background01.geometry}
				material={materials["マテリアル.001"]}
				scale={[-42.63, -26.574, -42.63]}
			/>
			<mesh
				geometry={nodes.background02.geometry}
				material={materials.マテリアル}
				scale={[-42.63, -26.574, -42.63]}
			/>
			<mesh
				geometry={nodes.chairshadow.geometry}
				material={materials["マテリアル.003"]}
				scale={[-42.63, -26.574, -42.63]}
			/>
			<mesh
				geometry={nodes.FL01.geometry}
				material={materials["マテリアル.013"]}
				scale={[-42.63, -26.574, -42.63]}
			/>
		</group>
	);
}

useGLTF.preload("/chairs001_2511072051_bake07.glb");
