/**
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Command: npx gltfjsx@6.5.3 chairs001_2511072051_bake07.glb
 *
 * @format
 */

import React, { useEffect, useRef, Suspense } from "react";
import { useGLTF, Center } from "@react-three/drei";
import { convertStandardToBasic } from "../utils/convertToBasic";

function GLB({ url, position = [0, 0, 0], rotation = [0, 0, 0], scale = 1, ...props }) {
	const group = useRef();
	const { scene } = useGLTF(url);

	useEffect(() => {
		if (!group.current) return;

		scene.position.set(0, 0, 0);
		scene.rotation.set(0, 0, 0);
		scene.scale.set(1, 1, 1);
		scene.updateMatrixWorld(true);

		convertStandardToBasic(group.current, { alphaTest: 0.55, setSRGBOnMap: true });
	}, []);

	return (
		<group ref={group} position={position} rotation={rotation} scale={scale} {...props}>
			<Center disableY>
				<primitive object={scene} />
			</Center>
		</group>
	);
}

function Backgrounds({
	url = "/models/chairs/backgrounds.glb",
	commonScale = [-42.63, -26.574, -42.63],
}) {
	const group = useRef();
	const { nodes } = useGLTF(url);

	useEffect(() => {
		if (!group.current) return;
		convertStandardToBasic(group.current, { alphaTest: 0.55, setSRGBOnMap: true });
	}, []);

	const b1 = nodes.background01;
	const b2 = nodes.background02;
	const ch = nodes.chairshadow;
	const fl = nodes.FL01;

	return (
		<group ref={group}>
			{b1 && <primitive object={b1} scale={commonScale} />}
			{b2 && <primitive object={b2} scale={commonScale} />}
			{ch && <primitive object={ch} scale={commonScale} />}
			{fl && <primitive object={fl} scale={commonScale} />}
		</group>
	);
}

const CHAIRS = [
	{
		url: "/models/chairs-portfolio_01-v1.glb",
		position: [0, 0, 12],
		rotation: [0, 0, 0],
	},
	{
		url: "/models/chairs-portfolio_02-v1.glb",
		position: [6, 0, 10.392],
		rotation: [0, 0, 0],
	},
	{
		url: "/models/chairs-portfolio_03-v1.glb",
		position: [10.392, 0, 6],
		rotation: [0, 0, 0],
	},
	{
		url: "/models/chairs-portfolio_04-v1.glb",
		position: [12, 0, 0],
		rotation: [0, 0, 0],
	},
	{
		url: "/models/chairs-portfolio_05-v1.glb",
		position: [10.392, 0, -6],
		rotation: [0, 0, 0],
	},
	{
		url: "/models/chairs-portfolio_06-v1.glb",
		position: [6, 0, -10.392],
		rotation: [0, 0, 0],
	},
	{
		url: "/models/chairs-portfolio_07-v1.glb",
		position: [0, 0, -12],
		rotation: [0, 0, 0],
	},
	{
		url: "/models/chairs-portfolio_08-v1.glb",
		position: [-6, 0, -10.392],
		rotation: [0, 0, 0],
	},
	{
		url: "/models/chairs-portfolio_09-v1.glb",
		position: [-10.392, 0, -6],
		rotation: [0, 0, 0],
	},
	{
		url: "/models/chairs-portfolio_10-v1.glb",
		position: [-12, 0, 0],
		rotation: [0, 0, 0],
	},
	{
		url: "/models/chairs-portfolio_11-v1.glb",
		position: [-10.392, 0, 6],
		rotation: [0, 0, 0],
	},
	{
		url: "/models/chairs-portfolio_12-v1.glb",
		position: [-6, 0, 10.392],
		rotation: [0, 0, 0],
	},
];

CHAIRS.forEach((p) => useGLTF.preload(p.url));
useGLTF.preload("/models/chairs-portfolio_background-v1.glb");

export default function Chairs(props) {
	return (
		<group {...props}>
			<Suspense fallback={null}>
				{CHAIRS.map((part, i) => (
					<GLB key={i} {...part} />
				))}
				<Backgrounds url="/models/chairs-portfolio_background-v1.glb" />
			</Suspense>
		</group>
	);
}
